### ISSUE TITLE
Compatibility with C# LibLog?

### ISSUE THREAD

**Issue by jimmcslim** [TheAngryByrd/FsLibLog#2]
I'm assuming that this isn't currently compatible with C#'s LibLog? i.e. Can I write a library in F# that is otherwise a good CLR citizen, and exports a LibLog that can be used alongside other C# libraries that also use LibLog?

**Comment by TheAngryByrd** [comment]
I haven't actually tested this scenario but if you have a C# console app that pulls in a F# library with FsLibLog and a C# library with LibLog and have setup Serilog (if you need support for another provider issues/PRs welcome! 😃 ), I don't see this being a problem since this is really the same scenario as two different C# libraries with LibLog.

**Comment by TheAngryByrd** [comment]
Closing for now, feel free to reopen if this does have an incompatibility.
